# Generated by Django 4.0 on 2021-12-24 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='date',
        ),
    ]
