# Generated by Django 4.0 on 2021-12-24 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_created_at_product_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date',
            new_name='created_at',
        ),
    ]
